# Create a program that will play the “cows and bulls” game with the user. The game works like this:

# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number(Digits should not be repeated). For every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

# Say the number generated by the computer is 1038. An example interaction could look like this:

#   Welcome to the Cows and Bulls Game! 
#   Enter a number: 
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1250
#   1 cow, 1 bull
#   ...
# Until the user guesses the number.

import random
class CowAndBullGame:
    
    def __init__(self):
        self.random_num = random.randint(1000,9999)

    def count_cowandbull(self, num):
        num_str = str(num)
        rand_str = str(self.random_num)

        cow_cnt = 0
        bull_cnt = 0

        for i in range(0,4):
            if num_str[i] == rand_str[i]:
                cow_cnt +=1
            else:
                bull_cnt +=1
        return cow_cnt, bull_cnt

    def play(self):
        game_status = 1
        guess_cnt = 0
        while game_status:
            num = input("Take a guess of 4 digit number or press q to quit the game:\n")

            if num == 'q' or num == "Q":
                game_status = 0
                return game_status, guess_cnt
            
            num = int(num)

            guess_cnt +=1
            cow_cnt, bull_cnt = self.count_cowandbull(num)

            if(bull_cnt == 0):
                return game_status, guess_cnt
            else:
                print("Cow Count :",cow_cnt,"\nBull Count :",bull_cnt,"\n")





play_status = 1
print("Welcome to the Cow and Bull Game!!!\n")
print("Rules of the game:\n1)You have to guess a 4 digit number\n2)You will get cow-cnt and bull-cnt\n3)cow-cnt indicates how many digits are correct and are in appropriate place  and bull-cnt indicates how many digits are wrong\n\nLets Start the game\n")
while play_status == 1:
    obj = CowAndBullGame()
    game_status, guess_taken = obj.play()
    if game_status == 1:
        print("Congratulations!! You have guessed correct number in ",guess_taken," attempt")
    else:
        print("You have Quit the game\n You have taken ", guess_taken," attempt")

    play_status = int(input("Do you want to play one more time :\nPress 1-> Yes\nPress 0 -> No\n"))